name: release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-22.04
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Login to Docker Hub
        if: github.repository_owner == 'k3s-io'
        uses: docker/login-action@v3
        with:
          username: k3s-io
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to Docker Hub (forks)
        if: github.repository_owner != 'k3s-io'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ github.repository_owner }}/klipper-lb:latest
            ${{ github.repository_owner }}/klipper-lb:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/klipper-lb:latest
            ghcr.io/${{ github.repository_owner }}/klipper-lb:${{ github.ref_name }}